Kurt/fnft metadata
bbproject01/bb-core pull request #5
Opened 2023-07-21 10:02 UTC by kd-singularity

Added MetaDataUpdate and batchMint

2023-07-22 13:44 UTC, hvstle-dev requested changes
Change parameter names for mintBatch() and follow FNFTMetadata variable names. You can also use FNFTMetadata struct and make it an array, instead of listing all variables as parameters.

2023-07-23 01:23 UTC, kd-singularity commented
Updated.

2023-07-23 02:44 UTC, hvstle-dev requested changes

2023-07-23 02:44 UTC, hvstle-dev commented on contracts/FNFTv2.sol
> +  function mint(IFNFT.Attributes memory fnftAttributes) public {
Replace IFNFT.Attributes to just Attributes. We inherited naman IFNFT so we don't need to do it like that

2023-07-23 05:08 UTC, merged